import { createHash } from "crypto";
import { and, eq, gt } from "drizzle-orm";
import { notFound } from "next/navigation";
import { db } from "@/db";
import { previewTokens, projects } from "@/db/schema";
import { Badge } from "@/components/ui/badge";
import { MermaidDiagram } from "@/components/site/mermaid-diagram";
import { CodeSample } from "@/components/site/code-sample";
export const dynamic="force-dynamic";export const metadata={robots:{index:false,follow:false}};
export default async function ProjectPreview({params}:{params:Promise<{token:string}>}){const{token}=await params;const hash=createHash("sha256").update(token).digest("hex");const[preview]=await db.select().from(previewTokens).where(and(eq(previewTokens.entityType,"PROJECT"),eq(previewTokens.tokenHash,hash),gt(previewTokens.expiresAt,new Date()))).limit(1);if(!preview)notFound();const[p]=await db.select().from(projects).where(eq(projects.id,preview.entityId)).limit(1);if(!p)notFound();return <main className="section-space"><article className="container-shell max-w-5xl"><div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm"><strong>Private preview.</strong> This case study is not necessarily public.</div><header className="mt-8 border-b border-border pb-8"><div className="flex gap-2"><Badge>{p.kind}</Badge><Badge>{p.lifecycleStatus.replaceAll("_"," ")}</Badge></div><h1 className="mt-4 text-4xl font-extrabold sm:text-5xl">{p.title}</h1><p className="mt-4 text-lg text-muted-foreground">{p.summary}</p></header><div className="mt-8 grid gap-6 lg:grid-cols-2">{[["Problem",p.problem],["Constraints",p.constraints],["Challenge",p.challenge],["Approach",p.solution],["Architecture",p.architecture],["Decisions",p.decisions],["Trade-offs",p.tradeoffs],["Implementation",p.implementation],["Reliability & security",p.reliabilitySecurity],["Impact",p.impact],["Lessons",p.lessonsLearned],["What I’d do differently",p.whatDifferently]].filter(([,v])=>v).map(([k,v])=><section key={String(k)} className="rounded-xl border border-border p-5"><h2 className="font-bold">{k}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{v}</p></section>)}</div>{p.diagrams?.map((d,i)=><div className="mt-6" key={i}><MermaidDiagram source={d.mermaid} title={d.title}/></div>)}{p.codeSamples?.map((c,i)=><div className="mt-6" key={i}><CodeSample {...c}/></div>)}</article></main>}
