import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, LibraryBig } from "lucide-react";
import { getPublishedSeries, getSeriesWithPosts } from "@/lib/platform-data";
import { getSitePage } from "@/lib/data";
import { actionTarget, itemValue, pageMetadata, sectionAction } from "@/lib/page-content";
import { PageHero } from "@/components/site/page-hero";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
export const dynamic="force-dynamic";
export async function generateMetadata():Promise<Metadata>{return pageMetadata(await getSitePage("series"))}
export default async function SeriesIndexPage(){const[series,page]=await Promise.all([getPublishedSeries().catch(()=>[]),getSitePage("series")]);if(!page)return null;const enriched=await Promise.all(series.map(async item=>{const data=await getSeriesWithPosts(item.slug).catch(()=>null);return{...item,articleCount:data?.posts.length??0}}));return <main className="section-space"><div className="container-shell flex flex-col gap-10">{page.sections.map(section=>{if(section.component==="PAGE_HERO")return <PageHero key={section.id} section={section}/>;if(section.component!=="SERIES_LIST")return null;const emptyAction=sectionAction(section,"blog");return <section key={section.id}>{enriched.length?<div className="grid gap-5 lg:grid-cols-2">{enriched.slice(0,section.itemLimit??enriched.length).map(item=><Card key={item.id} className="group overflow-hidden shadow-none transition-colors hover:border-primary/35"><CardContent className="p-0">{item.coverImage?<div className="aspect-[16/7] overflow-hidden border-b border-border bg-muted"><img src={item.coverImage} alt="" className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-[1.02]"/></div>:null}<div className="p-6"><div className="flex flex-wrap items-center gap-2"><Badge>{item.articleCount} {item.articleCount===1?itemValue(section,"articleSingular"):itemValue(section,"articlePlural")}</Badge></div><h2 className="mt-3 text-2xl font-extrabold tracking-tight"><Link href={`/series/${item.slug}`} className="hover:text-primary">{item.title}</Link></h2>{item.description?<p className="mt-3 text-sm leading-7 text-muted-foreground">{item.description}</p>:null}<Link href={`/series/${item.slug}`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">{itemValue(section,"exploreLabel")}<ArrowRight className="size-4"/></Link></div></CardContent></Card>)}</div>:<div className="rounded-2xl border border-dashed border-border p-10 text-center"><LibraryBig className="mx-auto size-7 text-primary"/><h2 className="mt-4 text-xl font-bold">{itemValue(section,"emptyTitle")}</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-muted-foreground">{itemValue(section,"emptyDescription")}</p>{emptyAction?<Link href={emptyAction.href} {...actionTarget(emptyAction)} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">{emptyAction.label}<ArrowRight className="size-4"/></Link>:null}</div>}</section>})}</div></main>}
