import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, ExternalLink } from "lucide-react";
import { GitHubIcon } from "@/components/site/brand-icons";
import { getPublishedProject, getSitePage } from "@/lib/data";
import { itemValue } from "@/lib/page-content";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { MermaidDiagram } from "@/components/site/mermaid-diagram";
import { CodeSample } from "@/components/site/code-sample";
import { db } from "@/db";
import { slugRedirects } from "@/db/schema";
import { and, eq } from "drizzle-orm";
import { getRelatedPostsForProject } from "@/lib/related";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const project=await getPublishedProject(slug);return project?{title:project.title,description:project.summary,alternates:{canonical:`/work/${project.slug}`},openGraph:{type:"article",title:project.title,description:project.summary,images:[{url:`/work/${project.slug}/opengraph-image`}]}}:{}}
export default async function WorkPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;let project=await getPublishedProject(slug);if(!project){const[mapped]=await db.select().from(slugRedirects).where(and(eq(slugRedirects.entityType,"PROJECT"),eq(slugRedirects.fromSlug,slug))).limit(1);if(mapped)redirect(`/work/${mapped.toSlug}`);notFound();}const[relatedPosts,page]=await Promise.all([getRelatedPostsForProject(project.techStack??[],project.kind),getSitePage("project-detail")]);if(!page)return null;const fields=Object.fromEntries(Object.entries(project));return <main className="section-space"><article className="container-shell flex flex-col gap-14">{page.sections.map(section=>{
  if(section.component==="PROJECT_HEADER")return <section key={section.id}><Link href="/work" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ArrowLeft className="size-4"/>{itemValue(section,"backLabel")}</Link><header className="mt-10 border-b border-border pb-12"><div className="flex flex-wrap items-center gap-2"><p className="section-kicker">{project.kind}</p>{project.lifecycleStatus?<Badge>{itemValue(section,project.lifecycleStatus)}</Badge>:null}</div><h1 className="mt-4 max-w-5xl text-balance text-4xl font-extrabold tracking-[-.045em] sm:text-6xl">{project.title}</h1><p className="mt-6 max-w-4xl text-lg leading-8 text-muted-foreground">{project.summary}</p><div className="mt-6 flex flex-wrap gap-2">{project.techStack.map(tech=><Badge key={tech}>{tech}</Badge>)}</div><div className="mt-7 flex flex-wrap gap-3">{project.externalUrl?<Button asChild variant="outline"><Link href={project.externalUrl} target="_blank">{itemValue(section,"siteLabel")}<ExternalLink className="size-4"/></Link></Button>:null}{project.repoUrl?<Button asChild variant="outline"><Link href={project.repoUrl} target="_blank">{itemValue(section,"repoLabel")}<GitHubIcon className="size-4"/></Link></Button>:null}</div>{project.confidentialityNote?<p className="mt-6 max-w-4xl text-sm leading-6 text-muted-foreground">{project.confidentialityNote}</p>:null}</header></section>;
  if(section.component==="PROJECT_METRICS"){if(!project.metrics.length)return null;return <section key={section.id}>{section.eyebrow?<p className="section-kicker">{section.eyebrow}</p>:null}{section.title?<h2 className="mt-2 text-3xl font-extrabold">{section.title}</h2>:null}<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{project.metrics.slice(0,section.itemLimit??project.metrics.length).map(metric=><Card key={metric.label} className="shadow-none"><CardContent className="p-5"><div className="text-2xl font-extrabold text-primary">{metric.value}</div><div className="mt-1 text-sm text-muted-foreground">{metric.label}</div></CardContent></Card>)}</div></section>}
  if(section.component==="PROJECT_NARRATIVE")return <section key={section.id} className="grid gap-8 lg:grid-cols-2">{section.items.map(item=>{const body=fields[item.key??""];if(typeof body!=="string"||!body)return null;return <div key={item.id} className="rounded-2xl border border-border bg-card p-6">{item.subtitle?<p className="section-kicker">{item.subtitle}</p>:null}{item.title?<h2 className="mt-2 text-2xl font-bold">{item.title}</h2>:null}<p className="mt-4 whitespace-pre-wrap leading-8 text-muted-foreground">{body}</p></div>})}</section>;
  if(section.component==="PROJECT_DIAGRAMS"){if(!project.diagrams?.length)return null;return <section key={section.id}>{section.eyebrow?<p className="section-kicker">{section.eyebrow}</p>:null}{section.title?<h2 className="mt-2 text-3xl font-extrabold">{section.title}</h2>:null}{section.description?<p className="mt-3 max-w-3xl text-muted-foreground">{section.description}</p>:null}<div className="mt-6 grid gap-6">{project.diagrams.slice(0,section.itemLimit??project.diagrams.length).map((d,i)=><MermaidDiagram key={`${d.title}-${i}`} title={d.title} source={d.mermaid} defaultTitle={itemValue(section,"defaultTitle")} renderingLabel={itemValue(section,"renderingLabel")}/>)}</div></section>}
  if(section.component==="PROJECT_CODE"){if(!project.codeSamples?.length)return null;return <section key={section.id}>{section.eyebrow?<p className="section-kicker">{section.eyebrow}</p>:null}{section.title?<h2 className="mt-2 text-3xl font-extrabold">{section.title}</h2>:null}{section.description?<p className="mt-3 max-w-3xl text-muted-foreground">{section.description}</p>:null}<div className="mt-6 grid gap-6">{project.codeSamples.slice(0,section.itemLimit??project.codeSamples.length).map((sample,i)=><CodeSample key={`${sample.title}-${i}`} {...sample} copyLabel={itemValue(section,"copyLabel")} copiedLabel={itemValue(section,"copiedLabel")}/>)}</div></section>}
  if(section.component==="RELATED_POSTS"){if(!relatedPosts.length)return null;return <section key={section.id}>{section.eyebrow?<p className="section-kicker">{section.eyebrow}</p>:null}{section.title?<h2 className="mt-2 text-3xl font-extrabold">{section.title}</h2>:null}{section.description?<p className="mt-3 max-w-3xl text-muted-foreground">{section.description}</p>:null}<div className="mt-6 grid gap-4 sm:grid-cols-2">{relatedPosts.slice(0,section.itemLimit??relatedPosts.length).map(post=><Card key={post.id}><CardContent className="p-5"><Link href={`/blog/${post.slug}`} className="text-lg font-bold hover:text-primary">{post.title}</Link><p className="mt-2 text-sm leading-6 text-muted-foreground">{post.excerpt}</p></CardContent></Card>)}</div></section>}
  if(section.component==="RICH_TEXT")return <section key={section.id} className="prose-portfolio rounded-2xl border border-border bg-muted/30 p-6 text-sm leading-6 text-muted-foreground">{section.eyebrow?<p className="section-kicker">{section.eyebrow}</p>:null}{section.title?<h2>{section.title}</h2>:null}{section.description?<p>{section.description}</p>:null}{section.body?<div dangerouslySetInnerHTML={{__html:section.body}}/>:null}</section>;
  return null;
})}</article></main>}
