import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, ExternalLink } from "lucide-react";
import { GitHubIcon } from "@/components/site/brand-icons";
import { getPublishedProject } from "@/lib/data";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { MermaidDiagram } from "@/components/site/mermaid-diagram";
import { CodeSample } from "@/components/site/code-sample";
import { db } from "@/db";
import { slugRedirects } from "@/db/schema";
import { and, eq } from "drizzle-orm";
import { getRelatedPostsForProject } from "@/lib/related";

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const project=await getPublishedProject(slug);return project?{title:project.title,description:project.summary,alternates:{canonical:`/work/${project.slug}`},openGraph:{type:"article",title:project.title,description:project.summary,images:[{url:`/work/${project.slug}/opengraph-image`}]}}:{title:"Case study not found"}}
const label=(value?:string|null)=>value?value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()):"";
export default async function WorkPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const project=await getPublishedProject(slug);if(!project){const [mapped]=await db.select().from(slugRedirects).where(and(eq(slugRedirects.entityType,"PROJECT"),eq(slugRedirects.fromSlug,slug))).limit(1);if(mapped)redirect(`/work/${mapped.toSlug}`);notFound();}const relatedPosts=await getRelatedPostsForProject(project.techStack??[],project.kind);const sections:Array<[string,string,string|null|undefined]>=[
["Problem","What problem existed before the work",project.problem],["Constraints","What the system had to respect",project.constraints],["Challenge","Why the problem was difficult",project.challenge],["Approach","How I approached it",project.solution],["Architecture","How the system was shaped",project.architecture],["Key decisions","Decisions and reasoning",project.decisions],["Trade-offs","What was deliberately accepted or rejected",project.tradeoffs],["Implementation","How the design moved into production",project.implementation],["Reliability & security","How correctness and failure were handled",project.reliabilitySecurity],["Impact","What changed",project.impact],["Lessons learned","What the work reinforced",project.lessonsLearned],["What I’d do differently","How I would improve the next iteration",project.whatDifferently],
];return <main className="section-space"><article className="container-shell max-w-6xl"><Link href="/work" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ArrowLeft className="size-4"/> All case studies</Link><header className="mt-10 border-b border-border pb-12"><div className="flex flex-wrap items-center gap-2"><p className="section-kicker">{project.kind}</p>{project.lifecycleStatus?<Badge>{label(project.lifecycleStatus)}</Badge>:null}</div><h1 className="mt-4 max-w-5xl text-balance text-4xl font-extrabold tracking-[-.045em] sm:text-6xl">{project.title}</h1><p className="mt-6 max-w-4xl text-lg leading-8 text-muted-foreground">{project.summary}</p><div className="mt-6 flex flex-wrap gap-2">{(project.techStack??[]).map(tech=><Badge key={tech}>{tech}</Badge>)}</div><div className="mt-7 flex flex-wrap gap-3">{project.externalUrl?<Button asChild variant="outline"><Link href={project.externalUrl} target="_blank">Project site <ExternalLink className="size-4"/></Link></Button>:null}{project.repoUrl?<Button asChild variant="outline"><Link href={project.repoUrl} target="_blank">Repository <GitHubIcon className="size-4"/></Link></Button>:null}</div>{project.confidentialityNote?<p className="mt-6 max-w-4xl text-sm leading-6 text-muted-foreground">{project.confidentialityNote}</p>:null}</header>
{(project.metrics??[]).length?<div className="my-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{project.metrics.map(metric=><Card key={metric.label} className="shadow-none"><CardContent className="p-5"><div className="text-2xl font-extrabold text-primary">{metric.value}</div><div className="mt-1 text-sm text-muted-foreground">{metric.label}</div></CardContent></Card>)}</div>:null}
<div className="grid gap-8 lg:grid-cols-2">{sections.filter(([, ,body])=>body).map(([kicker,title,body])=><section key={kicker} className="rounded-2xl border border-border bg-card p-6"><p className="section-kicker">{kicker}</p><h2 className="mt-2 text-2xl font-bold">{title}</h2><p className="mt-4 whitespace-pre-wrap leading-8 text-muted-foreground">{body}</p></section>)}</div>
{project.diagrams?.length?<section className="mt-14"><p className="section-kicker">Architecture</p><h2 className="mt-2 text-3xl font-extrabold">System diagrams</h2><div className="mt-6 grid gap-6">{project.diagrams.map((d,i)=><MermaidDiagram key={`${d.title}-${i}`} title={d.title} source={d.mermaid}/>)}</div></section>:null}
{project.codeSamples?.length?<section className="mt-14"><p className="section-kicker">Code</p><h2 className="mt-2 text-3xl font-extrabold">Sanitized implementation samples</h2><p className="mt-3 max-w-3xl text-muted-foreground">Representative patterns only. Private repositories, internal endpoints and employer-specific implementation details are intentionally omitted.</p><div className="mt-6 grid gap-6">{project.codeSamples.map((s,i)=><CodeSample key={`${s.title}-${i}`} {...s}/>)}</div></section>:null}
{relatedPosts.length?<section className="mt-14"><p className="section-kicker">Related writing</p><h2 className="mt-2 text-3xl font-extrabold">Engineering notes connected to this work</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{relatedPosts.map((post)=><Card key={post.id}><CardContent className="p-5"><Link href={`/blog/${post.slug}`} className="text-lg font-bold hover:text-primary">{post.title}</Link><p className="mt-2 text-sm leading-6 text-muted-foreground">{post.excerpt}</p></CardContent></Card>)}</div></section>:null}
<div className="mt-14 rounded-2xl border border-border bg-muted/30 p-6 text-sm leading-6 text-muted-foreground">Portfolio note: case studies involving employer or client systems intentionally describe architecture and outcomes at a high level. They do not expose confidential source code, credentials, internal endpoints or restricted operational details.</div></article></main>}
