import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BriefcaseBusiness } from "lucide-react";
import { getPublishedProjects, getSitePage } from "@/lib/data";
import { itemValue, pageMetadata } from "@/lib/page-content";
import { PageHero } from "@/components/site/page-hero";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
export const dynamic="force-dynamic";
export async function generateMetadata():Promise<Metadata>{return pageMetadata(await getSitePage("work"))}
export default async function WorkIndexPage(){const[projects,page]=await Promise.all([getPublishedProjects(),getSitePage("work")]);if(!page)return null;return <main className="section-space"><div className="container-shell flex flex-col gap-10">{page.sections.map(section=>{if(section.component==="PAGE_HERO")return <PageHero key={section.id} section={section}/>;if(section.component!=="PROJECT_LIST")return null;return <section key={section.id}>{projects.length?<div className="grid gap-6 lg:grid-cols-2">{projects.slice(0,section.itemLimit??projects.length).map(project=><Card key={project.id} className="group flex flex-col shadow-none transition-colors hover:border-primary/35"><CardHeader className="flex-1"><div className="flex flex-wrap items-center gap-2"><Badge>{project.lifecycleStatus?itemValue(section,project.lifecycleStatus):""}</Badge><span className="text-xs font-semibold uppercase tracking-[.12em] text-primary">{project.kind}</span></div><CardTitle className="mt-3 text-2xl"><Link href={`/work/${project.slug}`} className="hover:text-primary">{project.title}</Link></CardTitle><CardDescription className="mt-3 text-[15px] leading-7">{project.summary}</CardDescription><div className="mt-5 flex flex-wrap gap-2">{project.techStack.slice(0,6).map(tech=><Badge key={tech}>{tech}</Badge>)}</div></CardHeader><CardContent>{project.metrics.length?<div className="mb-5 grid grid-cols-2 gap-3">{project.metrics.slice(0,2).map(metric=><div key={metric.label} className="rounded-xl bg-muted p-3"><strong className="block text-foreground">{metric.value}</strong><span className="mt-1 block text-xs text-muted-foreground">{metric.label}</span></div>)}</div>:null}<Link href={`/work/${project.slug}`} className="inline-flex items-center gap-2 text-sm font-bold text-primary">{itemValue(section,"readLabel")}<ArrowRight className="size-4"/></Link></CardContent></Card>)}</div>:<div className="rounded-2xl border border-dashed border-border p-10 text-center"><BriefcaseBusiness className="mx-auto size-7 text-primary"/><h2 className="mt-4 text-xl font-bold">{itemValue(section,"emptyTitle")}</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-muted-foreground">{itemValue(section,"emptyDescription")}</p></div>}</section>})}</div></main>}
