import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpenText, Rss, SearchX } from "lucide-react";
import { getPublishedPosts, getSitePage, type PublicPageSection } from "@/lib/data";
import { actionTarget, itemValue, pageMetadata, sectionAction } from "@/lib/page-content";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { NewsletterForm } from "@/components/newsletter/newsletter-form";
import { PageHero } from "@/components/site/page-hero";
import { formatDate } from "@/lib/utils";
export const dynamic="force-dynamic";
export async function generateMetadata():Promise<Metadata>{return pageMetadata(await getSitePage("blog"))}
function newsletterCopy(section:PublicPageSection){return {emailPlaceholder:itemValue(section,"emailPlaceholder"),emailAria:itemValue(section,"emailAria"),submitLabel:itemValue(section,"submitLabel"),sendingLabel:itemValue(section,"sendingLabel"),privacyNote:itemValue(section,"privacyNote"),successTitle:itemValue(section,"successTitle"),errorTitle:itemValue(section,"errorTitle"),invalidTitle:itemValue(section,"invalidTitle"),invalidDescription:itemValue(section,"invalidDescription"),emailError:itemValue(section,"emailError"),localConfirmLabel:itemValue(section,"localConfirmLabel")}}
export default async function BlogPage({searchParams}:{searchParams:Promise<{category?:string;tag?:string;type?:string}>}){const params=await searchParams;const[allPosts,page]=await Promise.all([getPublishedPosts(),getSitePage("blog")]);if(!page)return null;const contentTypes=page.sectionMap.contentTypes;const posts=allPosts.filter(post=>(!params.category||post.categories.some(x=>x.toLowerCase()===params.category!.toLowerCase()))&&(!params.tag||post.tags.some(x=>x.toLowerCase()===params.tag!.toLowerCase()))&&(!params.type||post.contentType===params.type));const filtered=Boolean(params.category||params.tag||params.type);return <main className="section-space"><div className="container-shell flex flex-col gap-10">{page.sections.map(section=>{
  if(section.component==="PAGE_HERO"){const rss=sectionAction(section,"rss");return <section key={section.id} className="flex flex-col gap-6 border-b border-border pb-12 sm:flex-row sm:items-end sm:justify-between"><PageHero section={section}/>{rss?<Button asChild variant="outline"><Link href={rss.href} {...actionTarget(rss)}><Rss className="size-4"/>{rss.label}</Link></Button>:null}</section>}
  if(section.component==="BLOG_FILTERS"){if(!filtered)return null;return <section key={section.id} className="flex flex-wrap items-center gap-2"><span className="text-sm text-muted-foreground">{itemValue(section,"filteredBy")}</span>{params.category?<Badge className="border-primary/20 text-foreground">{itemValue(section,"categoryPrefix")}: {params.category}</Badge>:null}{params.tag?<Badge>{itemValue(section,"tagPrefix")}: {params.tag}</Badge>:null}{params.type?<Badge>{itemValue(contentTypes,params.type)}</Badge>:null}<Button asChild size="sm" variant="ghost"><Link href="/blog">{itemValue(section,"clearLabel")}</Link></Button></section>}
  if(section.component==="POST_LIST"){if(!posts.length)return null;return <section key={section.id} className="grid gap-6 md:grid-cols-2">{posts.slice(0,section.itemLimit??posts.length).map(post=><Card key={post.id} className="overflow-hidden transition-transform hover:-translate-y-1">{post.coverImage?<div className="aspect-[16/8] overflow-hidden bg-muted"><img src={post.coverImage} alt="" className="h-full w-full object-cover" loading="lazy"/></div>:null}<CardHeader><div className="flex flex-wrap gap-2"><Link href={`/blog?type=${encodeURIComponent(post.contentType)}`}><Badge>{itemValue(contentTypes,post.contentType)}</Badge></Link>{post.categories.map(category=><Link key={category} href={`/blog?category=${encodeURIComponent(category)}`}><Badge className="border-primary/20 text-foreground">{category}</Badge></Link>)}{post.tags.slice(0,4).map(tag=><Link key={tag} href={`/blog?tag=${encodeURIComponent(tag)}`}><Badge>{tag}</Badge></Link>)}</div><p className="pt-3 text-xs text-muted-foreground">{formatDate(post.publishedAt)} · {post.readingMinutes} {itemValue(section,"minuteLabel")}</p><CardTitle className="pt-1 text-2xl"><Link href={`/blog/${post.slug}`} className="hover:text-primary">{post.title}</Link></CardTitle><CardDescription className="text-[15px]">{post.excerpt}</CardDescription><Link href={`/blog/${post.slug}`} className="inline-flex items-center gap-2 pt-4 text-sm font-semibold text-primary">{itemValue(section,"readLabel")}<ArrowRight className="size-4"/></Link></CardHeader></Card>)}</section>}
  if(section.component==="EMPTY_STATE"){const shouldShow=section.key==="emptyFiltered"?filtered&&!posts.length:section.key==="empty"?!filtered&&!posts.length:false;if(!shouldShow)return null;const filteredStyle=section.key==="emptyFiltered";return <Card key={section.id} className="border-dashed"><CardContent className={filteredStyle?"py-12 text-center":"py-12"}>{filteredStyle?<SearchX className="mx-auto size-8 text-muted-foreground"/>:<BookOpenText className="size-9 text-primary"/>}{section.title?<h2 className={filteredStyle?"mt-4 text-xl font-bold":"mt-5 text-2xl font-extrabold"}>{section.title}</h2>:null}{section.description?<p className={filteredStyle?"mx-auto mt-2 max-w-xl text-muted-foreground":"mt-3 max-w-2xl leading-7 text-muted-foreground"}>{section.description}</p>:null}<div className={section.actions.length?"mt-6 flex flex-wrap gap-3 justify-center":""}>{section.actions.map(a=><Button key={a.id} asChild variant={a.variant==="PRIMARY"?"default":"outline"}><Link href={a.href} {...actionTarget(a)}>{a.label}{a.variant==="PRIMARY"?<ArrowRight className="size-4"/>:null}</Link></Button>)}</div></CardContent></Card>}
  if(section.component==="NEWSLETTER_SIGNUP")return <Card key={section.id}><CardHeader><CardTitle>{section.title}</CardTitle><CardDescription>{section.description}</CardDescription></CardHeader><CardContent><NewsletterForm compact copy={newsletterCopy(section)}/></CardContent></Card>;
  return null;
})}</div></main>}
