import Link from "next/link";
import { notFound } from "next/navigation";
import { getSeriesWithPosts } from "@/lib/platform-data";
import { getSitePage } from "@/lib/data";
import { itemValue } from "@/lib/page-content";
import { Card,CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
export const dynamic="force-dynamic";
export default async function SeriesPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const[data,page]=await Promise.all([getSeriesWithPosts(slug).catch(()=>null),getSitePage("series-detail")]);if(!data)notFound();if(!page)return null;const contentTypes=page.sectionMap.contentTypes;return <main className="section-space"><div className="container-shell flex flex-col gap-10">{page.sections.map(section=>{if(section.component==="SERIES_HEADER")return <header key={section.id}>{section.eyebrow?<p className="section-kicker">{section.eyebrow}</p>:null}<h1 className="section-title mt-3">{data.series.title}</h1>{data.series.description?<p className="mt-4 max-w-3xl text-lg leading-8 text-muted-foreground">{data.series.description}</p>:null}</header>;if(section.component!=="SERIES_POSTS")return null;return <section key={section.id} className="space-y-4">{data.posts.slice(0,section.itemLimit??data.posts.length).map((post,index)=><Card key={post.id}><CardContent className="grid gap-4 p-5 sm:grid-cols-[60px_1fr]"><div className="grid size-12 place-items-center rounded-xl bg-muted font-extrabold text-primary">{index+1}</div><div><div className="flex flex-wrap items-center gap-2"><Badge>{itemValue(contentTypes,post.contentType)}</Badge><span className="text-xs text-muted-foreground">{post.readingMinutes} {itemValue(section,"minuteLabel")}</span></div><h2 className="mt-2 text-xl font-bold"><Link href={`/blog/${post.slug}`} className="hover:text-primary">{post.title}</Link></h2><p className="mt-2 text-sm text-muted-foreground">{post.excerpt}</p></div></CardContent></Card>)}{!data.posts.length?<p className="text-muted-foreground">{itemValue(section,"emptyLabel")}</p>:null}</section>})}</div></main>}
